apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-v2-deployment
  labels:
    app: helloworld-v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld-v2
  template:
    metadata:
      labels:
        app: helloworld-v2
    spec:
      containers:
      - name: k8s-demo
        image: amitvashist7/k8s-tiny-web:4
        ports:
        - name: node-port
          containerPort: 80
      nodeSelector:
        hardware: virtual
