node('master') {
// Get Artifcatory Server Instance Details 
   def server = Artifactory.server "01"
   def buildInfo = Artifactory.newBuildInfo()

// Petclinic Project Variable
   def Project_Path="02-App-Code/petclinic-code"


stage('Git CheckOut') {
  git branch: 'main', url: 'https://github.com/shettydivyabailur/devcloud-dxc-30Mar2021.git'
 }

dir(Project_Path) {

stage('Clean') {
  sh 'mvn clean'
 }

stage('Compile') {
  sh 'mvn compile'
 }

stage('Testing') {
  sh 'mvn test'
 }

stage('Package') {
  sh 'mvn package'
 }

stage('Build Management') { 
    def uploadSpec = """{
     "files" : [
        { 
          "pattern": "**/*.war",
          "target": "Petclinic-snapshot"
        }
      ]
   }"""
   server.upload spec: uploadSpec
 }

stage('Publish Build Info'){
  server.publishBuildInfo buildInfo
 }

stage('Archive Artifacts') { 
archiveArtifacts artifacts: 'target/*.war', followSymlinks: false 
 }

stage('Publish Test Results') {   
junit 'target/surefire-reports/TEST-*.xml'  
 }


stage('Deployment - PreProd') {   
  sh ' docker-compose up -d --build'
 }

}
}
