nginx: 
  image: nginx:latest
  ports:
    - '8090:80'


mywebserver:
  image: myapache:v3
  ports:
    - '8091:80'

Mywebserver2:
   image: myapache:v4
   ports:
     - '80'

mywebserver3:
        image: myapache:v5
       
