apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: hello-k8s-deploy
  name: hello-k8s-deploy
  namespace: myspace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-k8s-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hello-k8s-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
